export const paperContent = {
  title: "The Incompleteness of Deductive Logic: A Generalization of Gödel's Theorem",
  sections: [
    {
      id: "abstract",
      title: "Abstract",
      content: "This paper demonstrates that deductive logic is incomplete, in the precise sense that there exists no recursive definition of the class of all logical truths. By generalizing Gödel's incompleteness theorem, it is shown that the class of recursively defined logics is not itself recursively definable. The core result rests on a cardinality mismatch between recursive definitions and their power sets, echoing Cantor's diagonal argument. The conclusion is that no logic, understood as a formal system, can capture the entirety of logical truth."
    },
    {
      id: "introduction",
      title: "1. Introduction and Framework",
      content: "We work in the context of classical first-order logic with equality, enriched by standard recursion theory. All sets and functions are assumed to be definable within ZFC set theory unless otherwise stated. A logic is formally defined as a recursively enumerable set of sentences φ ∈ Σ*, where Σ is a finite alphabet. Each such logic is generated by a pair (S, Φ), where S is a finite base of axioms and Φ is a recursive inference operator. The deductive closure of (S, Φ) determines the logic's scope of provable truths."
    },
    {
      id: "definitions",
      title: "2. Definitions",
      content: "Definition 2.1 (Recursive Function): A function f: ℕ → ℕ is recursive if there exists a Turing machine M such that for all n ∈ ℕ, M halts on input n and outputs f(n). Definition 2.2 (Posterity of α with respect to Φ): Let Φ be a recursive operator on Σ*. Define Post(α, Φ) as the smallest set k such that: 1. α ∈ k, 2. ∀x ∈ Σ*, if ∃y ∈ k such that Φ(y) = x, then x ∈ k. Definition 2.3 (Recursive Logic): A logic L is defined by a pair (S, Φ) with S ⊆ Σ* finite and Φ a recursive operator. The logic L consists of all sentences derivable from S under Φ."
    },
    {
      id: "theorems",
      title: "3. Lemmas and Theorems",
      content: "Lemma 3.1 (Cantor): |P(K)| > |K| for any set K. Proof Sketch: Assume |P(K)| = |K|. Then the diagonal subset of K cannot be in the image of any function f: K → P(K), contradicting surjectivity. □ Lemma 3.2: There is no recursive definition of the real numbers ℝ. Proof: Any recursive enumeration of rationals can be diagonalized to generate a real not in the list. □ Theorem 3.3: The class of all recursive definitions (K) is not recursively definable. Proof: Assume K is recursively definable. By Lemma 3.1, |P(K)| > |K|, but any recursive definition of K would imply P(K) is also recursively enumerable, yielding |P(K)| ≤ |K|, a contradiction. □"
    },
    {
      id: "significance",
      title: "4. Philosophical Significance",
      content: "Gödel's incompleteness theorem showed the limits of formal arithmetic. This paper extends that insight to logic itself. Any recursive system of logical truth generation (i.e., any formal logic) is inherently incomplete—not merely because of the limits of that system, but because the very class of such systems defies recursive definition. This underscores a fundamental limit to mechanized reasoning: there is no algorithmic means to capture logical truth in its entirety. Formal systems can approximate logical truth but never exhaust it. The result provides a metatheoretic foundation for understanding the necessary incompleteness of any computational approach to logic."
    },
    {
      id: "conclusion",
      title: "5. Conclusion",
      content: "This paper generalizes Gödel's incompleteness result from arithmetic to deductive logic as such. By demonstrating that the class of all recursively defined logics is not recursively definable, it reveals the deeper reason for logical incompleteness: the cardinality mismatch between recursion and its own power set. No formal system, however broadly defined, can exhaust the space of logical truths. This result provides a metatheoretic capstone to Gödel's original insight. □"
    },
    {
      id: "references",
      title: "References",
      content: "Gödel, K. (1931). Über formal unentscheidbare Sätze der Principia Mathematica und verwandter Systeme I. Monatshefte für Mathematik und Physik, 38(1), 173–198. Turing, A. M. (1936). On computable numbers, with an application to the Entscheidungsproblem. Proceedings of the London Mathematical Society, 2(42), 230–265. Church, A. (1936). An unsolvable problem of elementary number theory. American Journal of Mathematics, 58(2), 345–363. Tarski, A. (1936). Der Wahrheitsbegriff in den formalisierten Sprachen. Studia Philosophica, 1, 261–405."
    }
  ]
};
