export const paperContent = {
  title: "The Art of War",
  author: "Sun Tzu",
  sections: [
    {
      id: "laying-plans",
      title: "Chapter I: Laying Plans - The Foundations of Strategy",
      content: "Sun Tzu said: The art of war is of vital importance to the State. It is a matter of life and death, a road either to safety or to ruin. Hence it is a subject of inquiry which can on no account be neglected.\n\nThe art of war is governed by five constant factors, to be taken into account in one's deliberations when seeking to determine the conditions obtaining in the field. These are: The Moral Law, Heaven, Earth, The Commander, and Method and discipline.\n\nThe MORAL LAW causes the people to be in complete accord with their ruler, so that they will follow him regardless of their lives, undismayed by any danger. HEAVEN signifies night and day, cold and heat, times and seasons. EARTH comprises distances, great and small; danger and security; open ground and narrow passes; the chances of life and death.\n\nThe COMMANDER stands for the virtues of wisdom, sincerity, benevolence, courage and strictness. By METHOD AND DISCIPLINE are to be understood the marshaling of the army in its proper subdivisions, the graduations of rank among the officers, the maintenance of roads by which supplies may reach the army, and the control of military expenditure.\n\nThese five heads should be familiar to every general: he who knows them will be victorious; he who knows them not will fail. Therefore, in your deliberations, when seeking to determine the military conditions, let them be made the basis of comparison: Which of the two sovereigns is imbued with the Moral law? Which of the two generals has most ability? With whom lie the advantages derived from Heaven and Earth? On which side is discipline most rigorously enforced? Which army is stronger? On which side are officers and men more highly trained? In which army is there the greater constancy both in reward and punishment?\n\nBy means of these seven considerations I can forecast victory or defeat. All warfare is based on deception. Hence, when able to attack, we must seem unable; when using our forces, we must seem inactive; when we are near, we must make the enemy believe we are far away; when far away, we must make him believe we are near.\n\nHold out baits to entice the enemy. Feign disorder, and crush him. If he is secure at all points, be prepared for him. If he is in superior strength, evade him. If your opponent is of choleric temper, seek to irritate him. Pretend to be weak, that he may grow arrogant. If he is taking his ease, give him no rest. If his forces are united, separate them. Attack him where he is unprepared, appear where you are not expected."
    },
    {
      id: "waging-war",
      title: "Chapter II: Waging War - The Economics of Conflict",
      content: "Sun Tzu said: In the operations of war, where there are in the field a thousand swift chariots, as many heavy chariots, and a hundred thousand mail-clad soldiers, with provisions enough to carry them a thousand li, the expenditure at home and at the front, including entertainment of guests, small items such as glue and paint, and sums spent on chariots and armor, will reach the total of a thousand ounces of silver per day. Such is the cost of raising an army of 100,000 men.\n\nWhen you engage in actual fighting, if victory is long in coming, then men's weapons will grow dull and their ardor will be damped. If you lay siege to a town, you will exhaust your strength. Again, if the campaign is protracted, the resources of the State will not be equal to the strain.\n\nNow, when your weapons are dulled, your ardor damped, your strength exhausted and your treasure spent, other chieftains will spring up to take advantage of your extremity. Then no man, however wise, will be able to avert the consequences that must ensue.\n\nTherefore I have heard of stupid haste in war, but cleverness has never been seen associated with long delays. There is no instance of a country having benefited from prolonged warfare.\n\nIt is only one who is thoroughly acquainted with the evils of war that can thoroughly understand the profitable way of carrying it on. The skillful soldier does not raise a second levy, neither are his supply wagons loaded more than twice.\n\nBring war material with you from home, but forage on the enemy. Thus the army will have food enough for its needs. Poverty of the State exchequer causes an army to be maintained by contributions from a distance. Contributing to maintain an army at a distance causes the people to be impoverished.\n\nOn the other hand, the proximity of an army causes prices to go up; and high prices cause the people's substance to be drained away. When their substance is drained away, the peasantry will be afflicted by heavy exactions.\n\nWith this loss of substance and exhaustion of strength, the homes of the people will be stripped bare, and three-tenths of their income will be dissipated; while government expenses for broken chariots, worn-out horses, breast-plates and helmets, bows and arrows, spears and shields, protective mantles, draught-oxen and heavy wagons, will amount to four-tenths of its total revenue.\n\nHence a wise general makes a point of foraging on the enemy. One cartload of the enemy's provisions is equivalent to twenty of one's own, and likewise a single picul of his provender is equivalent to twenty from one's own store."
    },
    {
      id: "attack-by-stratagem",
      title: "Chapter III: Attack by Stratagem - Winning Without Fighting",
      content: "Sun Tzu said: In the practical art of war, the best thing of all is to take the enemy's country whole and intact; to shatter and destroy it is not so good. So, too, it is better to recapture an army entire than to destroy it, to capture a regiment, a detachment or a company entire than to destroy them.\n\nHence to fight and conquer in all your battles is not supreme excellence; supreme excellence consists in breaking the enemy's resistance without fighting. Thus the highest form of warfare is to attack the enemy's plans; next best is to attack his alliances; the next best is to attack his army; and the worst policy of all is to besiege walled cities.\n\nThe rule is, not to besiege walled cities if it can possibly be avoided. The preparation of mantlets, movable shelters, and various implements of war, will take up three whole months; and the piling up of mounds over against the walls will take three months more.\n\nThe general, unable to control his irritation, will launch his men to the assault like swarming ants, with the result that one-third of his men are slain, while the town still remains untaken. Such are the disastrous effects of a siege.\n\nTherefore the skillful leader subdues the enemy's troops without any fighting; he captures their cities without laying siege to them; he overthrows their kingdom without lengthy operations in the field.\n\nWith his forces intact he will dispute the mastery of the Empire, and thus, without losing a man, his triumph will be complete. This is the method of attacking by stratagem.\n\nIt is the rule in war, if our forces are ten to the enemy's one, to surround him; if five to one, to attack him; if twice as numerous, to divide our army into two. If equally matched, we can offer battle; if slightly inferior in numbers, we can avoid the enemy; if quite unequal in every way, we can flee from him.\n\nHence, though an obstinate fight may be made by a small force, in the end it must be captured by the larger force. Now the general is the bulwark of the State; if the bulwark is complete at all points, the State will be strong; if the bulwark is defective, the State will be weak.\n\nThere are three ways in which a ruler can bring misfortune upon his army: By commanding the army to advance or to retreat, being ignorant of the fact that it cannot obey. This is called hobbling the army. By attempting to govern an army in the same way as he administers a kingdom, being ignorant of the conditions which obtain in an army. This causes restlessness in the soldier's minds.\n\nBy employing the officers of his army without discrimination, through ignorance of the military principle of adaptation to circumstances. This shakes the confidence of the soldiers. But when the army is restless and distrustful, trouble is sure to come from the other feudal princes. This is simply bringing anarchy into the army, and flinging victory away."
    },
    {
      id: "tactical-dispositions",
      title: "Chapter IV: Tactical Dispositions - Form and Formlessness",
      content: "Sun Tzu said: The good fighters of old first put themselves beyond the possibility of defeat, and then waited for an opportunity of defeating the enemy. To secure ourselves against defeat lies in our own hands, but the opportunity of defeating the enemy is provided by the enemy himself.\n\nTherefore the good fighter is able to secure himself against defeat, but cannot make certain of defeating the enemy. Hence the saying: One may know how to conquer without being able to do it.\n\nSecurity against defeat implies defensive tactics; ability to defeat the enemy means taking the offensive. Standing on the defensive indicates insufficient strength; attacking, a superabundance of strength.\n\nThe general who is skilled in defense hides in the most secret recesses of the earth; he who is skilled in attack flashes forth from the topmost heights of heaven. Thus on the one hand we have ability to protect ourselves; on the other, a victory that is complete.\n\nTo see victory only when it is within the ken of the common herd is not the acme of excellence. Neither is it the acme of excellence if you fight and conquer and the whole Empire says, \"Well done!\"\n\nTo lift an autumn hair is no sign of great strength; to see the sun and moon is no sign of sharp sight; to hear the noise of thunder is no sign of a quick ear.\n\nWhat the ancients called a clever fighter is one who not only wins, but excels in winning with ease. Hence his victories bring him neither reputation for wisdom nor credit for courage.\n\nHe wins his battles by making no mistakes. Making no mistakes is what establishes the certainty of victory, for it means conquering an enemy that is already defeated.\n\nHence the skillful fighter puts himself into a position which makes defeat impossible, and does not miss the moment for defeating the enemy.\n\nThus it is that in war the victorious strategist only seeks battle after the victory has been won, whereas he who is destined to defeat first fights and afterwards looks for victory.\n\nThe consummate leader cultivates the moral law, and strictly adheres to method and discipline; thus it is in his power to control success.\n\nIn respect of military method, we have, firstly, Measurement; secondly, Estimation of quantity; thirdly, Calculation; fourthly, Balancing of chances; fifthly, Victory.\n\nMeasurement owes its existence to Earth; Estimation of quantity to Measurement; Calculation to Estimation of quantity; Balancing of chances to Calculation; and Victory to Balancing of chances.\n\nA victorious army opposed to a routed one, is as a pound's weight placed in the scale against a single grain. The onrush of a conquering force is like the bursting of pent-up waters into a chasm a thousand fathoms deep."
    },
    {
      id: "energy-weak-strong",
      title: "Chapter V: Energy - The Management of Force",
      content: "Sun Tzu said: The control of a large force is the same principle as the control of a few men: it is merely a question of dividing up their numbers.\n\nFighting with a large army under your command is nowise different from fighting with a small one: it is merely a question of instituting signs and signals.\n\nTo ensure that your whole host may withstand the brunt of the enemy's attack and remain unshaken—this is effected by maneuvers direct and indirect.\n\nThat the impact of your army may be like a grindstone dashed against an egg—this is effected by the science of weak points and strong.\n\nIn all fighting, the direct method may be used for joining battle, but indirect methods will be needed in order to secure victory.\n\nIndirect tactics, efficiently applied, are inexhaustible as Heaven and Earth, unending as the flow of rivers and streams; like the sun and moon, they end but to begin anew; like the four seasons, they pass away to return once more.\n\nThere are not more than five musical notes, yet the combinations of these five give rise to more melodies than can ever be heard.\n\nThere are not more than five primary colors (blue, yellow, red, white, and black), yet in combination they produce more hues than can ever been seen.\n\nThere are not more than five cardinal tastes (sour, acrid, salt, sweet, bitter), yet combinations of them yield more flavors than can ever be tasted.\n\nIn battle, there are not more than two methods of attack—the direct and the indirect; yet these two in combination give rise to an endless series of maneuvers.\n\nThe direct and the indirect lead on to each other in turn. It is like moving in a circle—you never come to an end. Who can exhaust the possibilities of their combination?\n\nThe onset of troops is like the rush of a torrent which will even roll stones along in its course.\n\nThe quality of decision is like the well-timed swoop of a falcon which enables it to strike and destroy its victim.\n\nTherefore the good fighter will be terrible in his onset, and prompt in his decision.\n\nEnergy may be likened to the bending of a crossbow; decision, to the releasing of a trigger.\n\nAmid the turmoil and tumult of battle, there may be seeming disorder and yet no real disorder at all; amid confusion and chaos, your array may be without head or tail, yet it will be proof against defeat.\n\nSimulated disorder postulates perfect discipline, simulated fear postulates courage; simulated weakness postulates strength.\n\nHiding order beneath the cloak of disorder is simply a question of subdivision; concealing courage under a show of timidity presupposes a fund of latent energy; masking strength with weakness is to be effected by tactical dispositions."
    },
    {
      id: "weak-points-strong",
      title: "Chapter VI: Weak Points and Strong - Water-like Adaptability",
      content: "Sun Tzu said: Whoever is first in the field and awaits the coming of the enemy, will be fresh for the fight; whoever is second in the field and has to hasten to battle will arrive exhausted.\n\nTherefore the clever combatant looks to the effect of combined energy, and does not require too much from individuals. Hence his ability to pick out the right men and utilize combined energy.\n\nWhen he utilizes combined energy, his fighting men become as it were like unto rolling logs or stones. For it is the nature of a log or stone to remain motionless on level ground, and to move when on a slope; if four-cornered, to come to a standstill, but if round-shaped, to go rolling down.\n\nThus the energy developed by good fighting men is as the momentum of a round stone rolled down a mountain thousands of feet in height. So much on the subject of energy.\n\nGenerally in war, the best policy is to take a state intact; to ruin it is inferior to this. To capture the enemy's army is better than to destroy it; to take a regiment, a company, or a five-man squad intact is better than to destroy them.\n\nFor to win one hundred victories in one hundred battles is not the acme of skill. To subdue the enemy without fighting is the acme of skill.\n\nTherefore, what is of supreme importance in war is to attack the enemy's strategy. Next best is to disrupt his alliances. The next best is to attack his army. The worst policy is to attack cities.\n\nAttack cities only when there is no alternative, because to prepare big shields and wagons and make ready the necessary arms and equipment will require at least three months, and to pile up earthen ramps against the walls will require another three months.\n\nIf the general cannot control his impatience and orders his troops to swarm up the wall like ants, one third of them will be killed without taking the city. This is the calamity of attacking cities.\n\nTherefore, those skilled in war subdue the enemy's army without battle. They capture his cities without assaulting them and overthrow his state without protracted operations.\n\nYour aim must be to take All-under-Heaven intact. Thus your troops are not worn out and your gains will be complete. This is the art of offensive strategy.\n\nConsequently, the art of using troops is this: When ten to the enemy's one, surround him. When five times his strength, attack him. If double his strength, divide him. If equally matched, you may engage him. If weaker numerically, be capable of withdrawing. And if in all respects unequal, be capable of eluding him, for a small force is but booty for one more powerful."
    },
    {
      id: "maneuvering-march",
      title: "Chapter VII: Maneuvering and The Army on the March",
      content: "Sun Tzu said: In war, the general receives his commands from the sovereign. Having collected an army and concentrated his forces, he must blend and harmonize the different elements thereof before pitching his camp.\n\nAfter that, comes tactical maneuvering, than which there is nothing more difficult. The difficulty of tactical maneuvering consists in turning the devious into the direct, and misfortune into gain.\n\nThus, to take a long and circuitous route, after enticing the enemy out of the way, and though starting after him, to contrive to reach the goal before him, shows knowledge of the artifice of deviation.\n\nManeuvering with an army is advantageous; with an undisciplined multitude, most dangerous.\n\nIf you set a fully equipped army in march in order to snatch an advantage, the chances are that you will be too late. On the other hand, to detach a flying column for the purpose involves the sacrifice of its baggage and stores.\n\nThus, if you order your men to roll up their buff-coats, and make forced marches without halting day or night, covering double the usual distance at a stretch, doing a hundred li in order to wrest an advantage, the leaders of all your three divisions will fall into the hands of the enemy.\n\nThe stronger men will be in front, the jaded ones will fall behind, and on this plan only one-tenth of your army will reach its destination.\n\nWe may take it then that an army without its baggage-train is lost; without provisions it is lost; without bases of supply it is lost.\n\nWe cannot enter into alliances until we are acquainted with the designs of our neighbors. We are not fit to lead an army on the march unless we are familiar with the face of the country—its mountains and forests, its pitfalls and precipices, its marshes and swamps. We shall be unable to turn natural advantage to account unless we make use of local guides.\n\nIn war, practice dissimulation, and you will succeed. Whether to concentrate or to divide your troops, must be decided by circumstances.\n\nLet your rapidity be that of the wind, your compactness that of the forest. In raiding and plundering be like fire, in immovability like a mountain. Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.\n\nWhen you plunder a countryside, let the spoil be divided amongst your men; when you capture new territory, cut it up into allotments for the benefit of the soldiery.\n\nPonder and deliberate before you make a move. He will conquer who has learned the artifice of deviation. Such is the art of maneuvering."
    }
  ]
};