export const paperContent = {
  title: "Tractatus Logico-Philosophicus",
  author: "Ludwig Wittgenstein", 
  sections: [
    {
      id: "the-world",
      title: "1. The World - Everything That Is the Case",
      content: "1 The world is everything that is the case.\n\n1.1 The world is the totality of facts, not of things.\n\n1.11 The world is determined by the facts, and by these being all the facts.\n\n1.12 For the totality of facts determines both what is the case, and also all that is not the case.\n\n1.13 The facts in logical space are the world.\n\n1.2 The world divides into facts.\n\n1.21 Any one can either be the case or not be the case, and everything else remain the same.\n\nWittgenstein begins with the fundamental thesis that reality consists of facts rather than things. The world is not a collection of objects but rather the totality of states of affairs that obtain. Facts are what make propositions true or false. The logical structure of the world determines what is possible and what is not."
    },
    {
      id: "atomic-facts",
      title: "2. Atomic Facts and Objects - The Substance of the World",
      content: "2 What is the case, the fact, is the existence of atomic facts.\n\n2.01 An atomic fact is a combination of objects (entities, things).\n\n2.011 It is essential to a thing that it can be a constituent part of an atomic fact.\n\n2.012 In logic nothing is accidental: if a thing can occur in an atomic fact the possibility of that atomic fact must already be prejudged in the thing.\n\n2.02 The object is simple.\n\n2.021 Objects form the substance of the world. Therefore they cannot be compound.\n\n2.0211 If the world had no substance, then whether a proposition had sense would depend on whether another proposition was true.\n\n2.0212 It would then be impossible to form a picture of the world (true or false).\n\n2.1 We make to ourselves pictures of facts.\n\n2.11 The picture presents the facts in logical space, the existence and non-existence of atomic facts.\n\n2.12 The picture is a model of reality.\n\nAtomic facts are combinations of simple objects. Objects are the unalterable substance of the world—they cannot be compound and exist independently of what is the case. The crucial insight is that we make pictures of facts, not things. These pictures share logical form with reality, allowing language to represent the world."
    },
    {
      id: "pictures-propositions",
      title: "3. Pictures and Propositions - The Logical Picture of Facts",
      content: "3 The logical picture of the facts is the thought.\n\n3.001 'An atomic fact is thinkable'—means: we can imagine it.\n\n3.01 The totality of true thoughts is a picture of the world.\n\n3.02 The thought contains the possibility of the state of affairs which it thinks. What is thinkable is also possible.\n\n3.03 We cannot think anything unlogical, for otherwise we should have to think unlogically.\n\n3.1 In the proposition the thought is expressed perceptibly through the senses.\n\n3.11 We use the sensibly perceptible sign (sound or written sign, etc.) of the proposition as a projection of the possible state of affairs.\n\n3.12 The sign through which we express the thought I call the propositional sign. And the proposition is the propositional sign in its projective relation to the world.\n\n3.14 The propositional sign consists in the fact that its elements, the words, are combined in it in a definite way. The propositional sign is a fact.\n\n3.203 The name means the object. The object is its meaning.\n\nThoughts are logical pictures of facts. What can be thought is what is logically possible. The proposition expresses thought through sensible signs that project possible states of affairs. Names mean objects directly, and propositions achieve sense through the logical arrangement of names."
    },
    {
      id: "thought-language", 
      title: "4. Thought and Language - The Critique of Philosophy",
      content: "4 The thought is the significant proposition.\n\n4.001 The totality of propositions is the language.\n\n4.002 Language disguises the thought; so that from the external form of the clothes one cannot infer the form of the thought they clothe, because the external form of the clothes is constructed with quite another object than to let the form of the body be recognized.\n\n4.003 Most propositions and questions, that have been written about philosophical matters, are not false, but senseless. We cannot, therefore, answer questions of this kind at all, but only state their senselessness.\n\n4.01 The proposition is a picture of reality. The proposition is a model of the reality as we think it is.\n\n4.022 The proposition shows its sense. The proposition shows how things stand, if it is true. And it says, that they do so stand.\n\n4.024 To understand a proposition means to know what is the case, if it is true.\n\n4.111 Philosophy is not one of the natural sciences.\n\n4.112 The object of philosophy is the logical clarification of thoughts. Philosophy is not a theory but an activity.\n\nMost traditional philosophical problems arise from misunderstanding the logic of language. Ordinary language disguises logical form. Philosophy should clarify thought rather than produce theories. Understanding a proposition means grasping what would make it true, not knowing whether it actually is true."
    },
    {
      id: "truth-functions",
      title: "5. Truth-Functions and Elementary Propositions",
      content: "5 Propositions are truth-functions of elementary propositions. (An elementary proposition is a truth-function of itself.)\n\n5.01 The elementary propositions are the truth-arguments of propositions.\n\n5.1 The truth-functions can be ordered in series. That is the foundation of the theory of probability.\n\n5.11 If the truth-grounds which are common to a number of propositions are all also truth-grounds of some one proposition, we say that the truth of this proposition follows from the truth of those propositions.\n\n5.3 All propositions are results of truth-operations on the elementary propositions.\n\n5.4 Here it becomes clear that there are no such things as 'logical objects' or 'logical constants' (in the sense of Frege and Russell).\n\n5.43 All propositions of logic say the same thing. That is, nothing.\n\n5.47 It is clear that everything which can be said beforehand about the form of all propositions at all can be said on one occasion.\n\n5.6 The limits of my language mean the limits of my world.\n\n5.61 Logic fills the world: the limits of the world are also its limits.\n\nAll meaningful propositions are truth-functions of elementary propositions. Logic reveals the scaffolding of language but says nothing about the world. The boundaries of meaningful language determine the boundaries of what can be thought and expressed."
    },
    {
      id: "ethics-mystical",
      title: "6. Ethics and the Mystical - What Cannot Be Said",
      content: "6.4 All propositions are of equal value.\n\n6.41 The sense of the world must lie outside the world. In the world everything is as it is and happens as it does happen. In it there is no value—and if there were, it would be of no value.\n\n6.42 Hence also there can be no ethical propositions. Propositions cannot express anything higher.\n\n6.421 It is clear that ethics cannot be expressed. Ethics are transcendental. (Ethics and æsthetics are one.)\n\n6.43 If good or bad willing changes the world, it can only change the limits of the world, not the facts; not the things that can be expressed in language.\n\n6.431 As in death, too, the world does not change, but ceases.\n\n6.44 Not how the world is, is the mystical, but that it is.\n\n6.45 The contemplation of the world sub specie aeterni is its contemplation as a limited whole. The feeling of the world as a limited whole is the mystical feeling.\n\n6.522 There is indeed the inexpressible. This shows itself; it is the mystical.\n\nThe ethical and mystical domains lie beyond meaningful language. Values and the meaning of existence cannot be stated in propositions. What we feel as the significance of life belongs to the mystical—it shows itself but cannot be said. Ethics and aesthetics are transcendental because they concern our attitude toward the world as a whole."
    },
    {
      id: "limits-silence",
      title: "7. The Limits of Language - Whereof One Cannot Speak",
      content: "6.53 The right method of philosophy would be this. To say nothing except what can be said, i.e. the propositions of natural science, i.e. something that has nothing to do with philosophy: and then always, when someone else wished to say something metaphysical, to demonstrate to him that he had given no meaning to certain signs in his propositions.\n\n6.54 My propositions are elucidatory in this way: he who understands me finally recognizes them as senseless, when he has climbed out through them, on them, over them. (He must so to speak throw away the ladder, after he has climbed up on it.) He must surmount these propositions; then he sees the world rightly.\n\n7 Whereof one cannot speak, thereof one must be silent.\n\nThe Tractatus concludes with its most famous proposition. Having shown the limits of meaningful language, Wittgenstein reveals that his own propositions transgress these limits. The ladder metaphor suggests that philosophical propositions serve a therapeutic purpose: they help us see clearly, after which we can recognize them as attempts to say what can only be shown. The final silence encompasses all that is most important but cannot be captured in language."
    }
  ]
};